0.2.2 branch
* Ttafsir lint refactor (#27)

* update README

* lint w/ sourcery

* add flake8 and editor configs

* adds pytest config

* Add tests/refactor failing

* add tests for network endpoints

* refactor tests/fixtures

* refactor/lint

* cleanup / reformat with Black

* Ttafsir docs (#28)

* Initial documentation

* add usage example

* updates modules documentation

* update quickstart

* Adds port to EveClient contructor (#31)

* removes extraneous methods and interface(s) (#43)

* create requirements files and move from poetry (#44)

* create requirements files and move from poetry
Fixes #38

* Adds pre-commit

* rename ci -> lint and updates linting

* fix linting issues

* Issue 46 update api module to use updated client (#47)

* Add API object on Client Init

* clean up and refactor

* Fix upload test

* Fix linting

* get_node_by_name not working Fixes #48 (#49)

Fixes #48
* provides more meaning messages in Exceptions based on returned JSON messages
* pulls response data from `data` key for node search

* refactors p2p & network links for topology builder (#51)

* Add missing `port` option to client. (#54)

Fixes #53

* Issue55-fix-lab_commands (#56)

* clean up

* fix api responses for lab commands

* fix  lab export command

* remove inventory command

* Fix Linting

* Issue55 fix lab commands (#57)

* clean up
* fix api responses for lab commands
* fix  lab export command
* remove inventory command
* Fix Linting
* clean up print statement

* clean up

* Adds overides for create-issue-branch (#60)

* Issue 61 fix node commands (#64)

* refactor api response parsing to list labs
* rename nodes -> node and fix api response parsing
* fix missing delete_node method
* lint: remove unused import

* Ttafsir/issue65_fix-system-commands (#66)

* fix system commands
* Adds tests

* fix failing tests (#68)

Fixes #67

* refactor-text-based-output 

* update requirements
* Adds console module to manage cli output
* refactor text based cli output

* Adds import lab feature

* refactor-table-based-output

* update table display to use rich table
* update CLI commands for updated table display

* Add error handling for empty node list

* Add topology schema

* Adds jsonschema
* Adds initial topology schema

* Adds Topology File builder

* Adds `configuration` to node schema
* Adds topology builder

* Adds startup-config retrieval

* Adds status for long running commands

* update docs and build scripts

* Updates setup scripts and update docs
* Adds publish workflow

* update docs and build scripts

* Updates setup scripts and update docs
* Adds publish workflow

* Update publish.yml

* Update publish.yml

fixing 
```
/opt/hostedtoolcache/Python/3.9.9/x64/bin/python: No module named build
Error: Process completed with exit code 1.
```

* 0.2.0 branch

* Bump urllib3 from 1.26.3 to 1.26.5 (#29)

Bumps [urllib3](https://github.com/urllib3/urllib3) from 1.26.3 to 1.26.5.
- [Release notes](https://github.com/urllib3/urllib3/releases)
- [Changelog](https://github.com/urllib3/urllib3/blob/main/CHANGES.rst)
- [Commits](https://github.com/urllib3/urllib3/compare/1.26.3...1.26.5)

---
updated-dependencies:
- dependency-name: urllib3
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Develop (#32)

* Ttafsir lint refactor (#27)

* update README

* lint w/ sourcery

* add flake8 and editor configs

* adds pytest config

* Add tests/refactor failing

* add tests for network endpoints

* refactor tests/fixtures

* refactor/lint

* cleanup / reformat with Black

* Ttafsir docs (#28)

* Initial documentation

* add usage example

* updates modules documentation

* update quickstart

* Adds port to EveClient contructor (#31)

* Develop (#40)

* Ttafsir lint refactor (#27)

* update README

* lint w/ sourcery

* add flake8 and editor configs

* adds pytest config

* Add tests/refactor failing

* add tests for network endpoints

* refactor tests/fixtures

* refactor/lint

* cleanup / reformat with Black

* Ttafsir docs (#28)

* Initial documentation

* add usage example

* updates modules documentation

* update quickstart

* Adds port to EveClient contructor (#31)

* Develop (#41)

* Ttafsir lint refactor (#27)

* update README

* lint w/ sourcery

* add flake8 and editor configs

* adds pytest config

* Add tests/refactor failing

* add tests for network endpoints

* refactor tests/fixtures

* refactor/lint

* cleanup / reformat with Black

* Ttafsir docs (#28)

* Initial documentation

* add usage example

* updates modules documentation

* update quickstart

* Adds port to EveClient contructor (#31)

* Develop (#42)

* Ttafsir lint refactor (#27)

* update README

* lint w/ sourcery

* add flake8 and editor configs

* adds pytest config

* Add tests/refactor failing

* add tests for network endpoints

* refactor tests/fixtures

* refactor/lint

* cleanup / reformat with Black

* Ttafsir docs (#28)

* Initial documentation

* add usage example

* updates modules documentation

* update quickstart

* Adds port to EveClient contructor (#31)

* 0.1.1 branch (#63)

* update requirements/deps management
* Adds pre-commit config
* Fix linting issues
* update version
* make library compatible to windows

The `Path` class does use OS-dependent directory separators, so `mylab.unl` becomes `\mylab.unl` on Windows and results in an error.
Using `.as_posix()` forces `/` as a separator and fixes that issue.

Co-authored-by: Martin Plattner <git@mplattner.at>

* update docs and build scripts

* Updates setup scripts and update docs
* Adds publish workflow

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Martin Plattner <git@mplattner.at>

* Update publish.yml

* Update due to conflicting name on pypi

* make library compatible to windows (#62)

The `Path` class does use OS-dependent directory separators, so `mylab.unl` becomes `\mylab.unl` on Windows and results in an error.
Using `.as_posix()` forces `/` as a separator and fixes that issue.

* Update documentation typos and navigation

* Fix typos and add navigation

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Martin Plattner <git@mplattner.at>

* Fix path for windows and minor updates

* make library compatible to windows (#62)

The `Path` class does use OS-dependent directory separators, so `mylab.unl` becomes `\mylab.unl` on Windows and results in an error.
Using `.as_posix()` forces `/` as a separator and fixes that issue.

* Update documentation typos and navigation

* Fix typos and add navigation

* fix configuration enable

* Adds method to enable config after upload

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Martin Plattner <git@mplattner.at>

* Update version.py

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Martin Plattner <git@mplattner.at>